logo = """
 ____ ___ _____ _   ___     _______ _   _ ___ ____   ___       _    
| __ )_ _| ____| \ | \ \   / / ____| \ | |_ _|  _ \ / _ \     / \   
|  _ \| ||  _| |  \| |\ \ / /|  _| |  \| || || | | | | | |   / _ \  
| |_) | || |___| |\  | \ V / | |___| |\  || || |_| | |_| |  / ___ \ 
|____/___|_____|_| \_|  \_/  |_____|_| \_|___|____/ \___/  /_/   \_\
                                                                    
    _    ____ _____     _____ _   _    _     __   __
   / \  |  _ \_ _\ \   / /_ _| \ | |  / \    \ \ / /
  / _ \ | | | | | \ \ / / | ||  \| | / _ \    \ V / 
 / ___ \| |_| | |  \ V /  | || |\  |/ ___ \    | |  
/_/   \_\____/___|  \_/  |___|_| \_/_/   \_\   |_|  
                                                    
  ____    _    _   _    _    _ 
 / ___|  / \  | \ | |  / \  | |
| |  _  / _ \ |  \| | / _ \ | |
| |_| |/ ___ \| |\  |/ ___ \|_|
 \____/_/   \_\_| \_/_/   \_(_)
                               
"""



cultura = """"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMXxooOWMMMMMMMMMMMMMMMMMMMMMMMMMMOxkkkO0KXNWWWWKKXXXXXXXWMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMK;     .oc;;;,:KMMMMMMMMMMMMMMMMMMWkddxxxxkkOOxdxxkxodxkx0MMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMo.     .oo.  ;ko,0MMMMMMMMMMMMMMMMMMMKdlllolldxxkOkddxkddkWMMMMMMMMMMMMWNWMMM
MMMMMMMMMMMMMMMMMW;       .,c..:xOkd0MMMMMMMMMMMMMMMMMMMMMKdl.  .,;:coxOOdoOMMMMMMMMMMKWN0OOKMMM
MMMMMMMMMMMMMMMMW,   ..   :c:okxdOdd0MMMMMMMMMMMMMMMMMMMMMMNc',.  ..  ..okO0WMMMMMMMMM0OOOOKWMMM
MMMMMMMMMMMMMMMW,  ...    XddkOOO0K0OMMMMMMMMMMMMMMMMMMMMMMcoxdloxk;    :xxkOXMMMMMMNl,:OKWMMMMM
MMMMMMMMMMMMMMN,....     .WMKOxkkOOOKMMMMMMMMMMMMMMMMMMMMMN:ooxOxock'   'ldxxkKMMMWo.  .kMMMMMMM
MMMMMMMMMMMMMc.....      :MWW0ok0O0XMMMMMMMMMMMMMMMMMMMMMWKooodkoxOOc.,'.lloxxkKNo. ...xMMMMMMMM
MMMMMMMMMMMMMN0kd;.     .ko'':ll',l0MMMMMMMMMMMMMMMMMMMMXxxOkxxkOOOc,xdkkxlloxd;. ....kMMMMMMMMM
MMMMMMMMMMMMMMMo.     .:kOx'''''''',oWMMMMMMMMMMMMMMMMMM0xkKXNXOOOOok0KWMMMXd,.     .0MMMMMMMMMM
MMMMMMMMMMMMMMMMXOxxxkkOOk:'''''',''':WMMMMMMMMMMMMMMMMMWOxkOkOOOOOO0MMNOl'.       ,XMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMNOOOXN'...'''....cOWMMMMMMMMMMMMMMKkdNN0xxkOO0Kx....         .dMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMXOOKWMMx.''....'';OkOXWMMMWNX0ko:'.  ,W0o:cMMMMk.           .oWMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMWKOOKWMMc'.;c;;;::ldkOOOk;.          .:;o:;0MK;      ..   ,xWMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWX0OKNk,,l0kxxdOOOxdddold:.        ,:x0:;k;      ....cxNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWOxxkdoxkkO000OloxdocokOo,.    'oO00c:0.    .... ;MMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMXxoooddddoooOMMMMMMMMMMMMM0.   ,O0000xk0.  ...   .KMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMWkoooooooooooodWMMMMMMMMMMMM.   .O0000000O.        lMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMM0dooooooooooooooNMMMMMMMMMMMMk.  o00000000O.       .WMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMKxooooooooooooooooKMMMMMMMMMMMMMN:.loddxxxxxk.     .cXMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMKxoooloooooooooooooo0MMMMMMMMMMMMMMK;;;;;;;;;;;'..'';NMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWKdooolloooooooooooloookMMMMMMMMMMMMMMWc;;;;;;;;;;;;;;;0MMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMW0doooollooooooooooooloooxMMMMMMMMMMMMMMMN:',,,,,,,,'',',OMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMNOdoooolclooooooloooooolloodWMMMMMMMMMMMMMMMd.          ,'';KMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMKdllooolccooooooolooddooolloooNMMMMMMMMMMMMMMMO          .;,.;:NMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMW0l:::::;;;cooooooocoddoooooccoooXMMMMMMMMMMMMMMMW.     .   .;, ;;cWMMMMMMMMMMMMMMMMMMMMMMMM
MMMOc:::::;;;,:lolllolcodoooooooccoolOMMMMMMMMMMMMMMMM'     x'  ,;; ,;;oMMMMMMMMMMMMMMMMMMMMMMMM
MMMKc:::;;,,;:::::::;,:ooooooooo;;:::dMMMMMMMMMMMMMMMMl     NX. ,;; c:;oMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMX0Okxl;:::::::;,;oooooooooo;,;::lMMMMMMMMMMMMMMMMk    .MM0..',.:O:NMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMO:::::::;,;:cclcccc:::;,,;::WMMMMMMMMMMMMMMMX    :MMMo..  'MMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNxl::::;,;::::::::::::;,,;::XMMMMMMMMMMMMMMMM.   xMMMW'   .MMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWWNWWo:::::::::::::;,,;cxXMMMMMMMMMMMMMMMMc   KMMMM0    XMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMN:::::::::::::::0NWMMMMMMMMMMMMMMMMMMMx   WMMMMM;   OMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWoko;xdoolllccllxNMMMMMMMMMMMMMMMMMMMMMX  'MMMMMMk   dMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMM:;,cNMMMMMMM0:kxOMMMMMMMMMMMMMMMMMMMMWXO,;dMMMMMMMd;;OMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMcdXMMMMMMMMMMx'l'WMMMMMMMMMMMMMMMNc,.. .. .MMMMMMMl.. 'l0MMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl,NMMMMMMMMMMMMMMMMMWNNNMWNNMMMMMMMMMW0xdxWMMMMMMMMMMMMMMMMMMMMMM
"""


cultura2 = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWWNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0O0OKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXNWNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKKX0kO00XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXXXNNK0OXNWWMMMMMMMMMMMMMMMWWMMMMMMMMMNKKXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXXNXXNWMMMMMMMMMMWXKK0KXWMMMMMN0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK0KKKNMMMMMW0xk000OkxOXWMWX0KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0dxOKWMMWX000KOddk00XNMWKOKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNN0k0NWW0O0xxOxx0KKNWWK0KNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMWXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOkOxkkOkO0xkO0WWNKKKXMMMMMMWNNWMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMX00XKXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOkO000kKK000KXX0X0NWMMMWXOxllddkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMWNNK0KKK0XNWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXKK0Ok0XKX0K0KKWMMWKkxdddlolx000XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMWWX0OkkkOk0KKKXXKXNWMMMMMMMMMMMMMMMMMMMMMMMMMNKKKK0O0k00Kk0WMMMW0oddddxdocllxKXXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWNX00kO0OO0OOKKXXWWWMMMMMMMMMMMMMMMMMMMWKOkOOkddO00OKWMMMWOkkxxxxxddooclol0WMMMMMMMMMMMMMM0xkO00KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMWNX0KXXOOXX0KKKXWWNXWWWMMMMMMMMMMMMWOox00KKOkkOKXWMMMMMMKdodxxxxxddllxNMMMMMMMMMMMMMWo        ...'cKMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWWNXKXXKKNN0KKKKKOXNXNNWWXXKKNNNXXWXKKXK00OkKWMMMMMMK0OkdxxxxxxoldKMMMMMMMMMMMMWl            :XMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXX0k0KKKkkOO00OOOKO0XNKXXXK0XNK00NWWMMMMMMMMMNxodxxxxkxccdONMMMMMMMMMNc           .oWMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXX0K0kOKKXXXNWX00K0KNNXKK0OKKKWMMMMMMMMMMMNKKXXKOoc;,,:lxKWMMMMMMK, ..         ;XMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKNWXXNNXXKK000OO0Ok0OxNWMMMMMMMMMMMMMMMMMMMW0c,;;;;:lkXWMMMO.  .;          .;ld0XWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWX0OkOKOkOK00OxOXWMMMMMMMMMMMMMMMMMMMMMMMN0l,;;;;coOXWx.    ,'               .';cldxkO0XNWMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0OO00O00OxO0XWMMMMMMMMMMMMMMMWNNWMMMMMMMMWOc,;;;;lox,      ;                          ...',;;ckWM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0Ok0OxdkXWMMMMMMMMMMMMMMMWNNNNWMMMMMMMMMMMXd;,,;;;col.    ';                                 .XM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxxx0KOONMMMMMMMMMMMMMMMWNXNWMMMMMMMMMMMMMMMWO:;,,;;:ld:    ;.                               ,KMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXkO00KKKWMMMMMMMMMMMMWNNXNWMMMMMMMMMMMMMMXOxoo:';;;,;:col.  ;;.                            ,xNMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWK0OOOOOWMMMMMMMMMWWNXXNWMMMMMMMMMMMMMMMK.      ';;;;;;:lo:..o'.                        .lKMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kk0K0WMMMMMMWNXXXNWMMMMMMMMMMMMMMMMWd.       , .';;;;;:oo,,:..                   .'lONMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXK00OkkkOOOkxddddxO0KXNNNXXNWMMMMMMMMMMMMMMX:,,,'        ..   .,;;;;;codd:''..........        .,,,,,,,;;;:K
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKOkdolcccc:cdOKXXXXX0klcccclx00kdkOKNWMMMMMMMMMMMMX.     .     . ..    ';;;;;::lo;                               0
MMMMMMMMMMMMMMMMMMMMMMMMWX0xoc:;;,,,,,;;:dXXXXXXXXXXOcok0K0Okxdoc:coxOKWMMMMWK0Oc              ..     .,;;;;;;col'          ...               .0
MMMMMMMMMMMMMMMMMMMMMW0xlcccc;,'''''''',:cdOKXXXXK00O0K0OkkkkkkkxlccccclxKWMk  ',,,,...      ...        .,;;;:::loc.     .cdlldc'..          .,X
MMMMMMMMMMMMMMMMMMMW0o:c:ccc:,'''''''',;:ccccooooxOKKOddxkkkkkkkkl:ccccccco00;.   ..,::;::...            .,:;;;;:coolkOO00xX0lcdOWWKo.  ...'cKMM
MMMMMMMMMMMMMMMMMWKdc::::::cc:;;,,,;;::cc:c:coxO000koc:ccloddddolcccccc:ccccd0XKOxoc,                    ..';;:;:;cldOXWWKkNWkcoxXMMM0...;KWMMMM
MMMMMMMMMMMMMMMMWkc::;;;;::cccccccccc:ccccokXWWX0dc:cccccccccccccc::::::::::ccdXMMMMMl.  cl'   ....      .;ldd:::::::lodkOXWW0lld0WMMW,. xMMMMMM
MMMMMMMMMMMMMMMWkc:;;;;;;::cccccccccccccoONWNKOxc:cccccccccccccccc:::::::::::ccoXMMMMd. .XMo...0x0X:'.  ;KWXOxoc::::::cOWWXk0XdcldOXNW: .KMMMMMM
MMMMMMMMMMMMMMWOc::;;;;;::ccccccccccccoOXWN0xlccccccccccccccccccccc:::::::::::c:kMMMMk. 'NMo.'.o0Wkk..  0WOdddddo:::cdOXWWMWXKOkxdooodl:ckOKXWMM
MMMMMMMMMMMMMMNd:c::;;:::ccccccccc::ckXN0xlcccccccccccccccccccccccccccc:::::ccccoNMMM0. ,WMo'' xXd0N'. .NOddxddddolxKNNNNNNWWkldKWNNNXXKOxdlldOX
MMMMMMMMMMMMMMWOcccc:ccccccccccc:;;;,:xl:cccccccccccccccccccccccccccccccccccccc::KMMMO. ;WMd',.0kXMM;  ,WkddxxddddxOXNNXK00NWNKXOooOWWNWMWWXklco
MMMMMMMMMMMMMMMWdcccllllllcccc:;,,,;::cccccccccccccccccccccccccccccccccccccc::;;OWMMd. ;XMWl..,kNMMMc  cMXxddxddddddkKK0KXNNK0k0N0xNNxdKMMMN0xoc
MMMMMMMMMMMMMMMMKcccloooooolc;'';;:ccccccccccc::;;;::ccccc:::ccccccccccc::;,,:dXMMMMNOkXMNx   .kMMMMc  lMMNOxdddddxddONNNNK0O0kdxKKXWXXNX0kxdddo
MMMMMMMMMMMMMMMMMkcclooooooolc::cccccccccccc;'.......,:cc::llc::;,,,,;;:cldOXWMMMMMMMMMMMXkol;:OMMMMc  lMMMMWXK0kdxdddkNXOO000O00OOXNKOxdddddddd
MMMMMMMMMMMMMMMMMW0c:cloooooolccccccccccccc:.         .cccKMMMMWNXXXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMO.. lWMMMMMMMMM0ddddd0XOO000OkxOOxxxdddddddddd
MMMMMMMMMMMMMMMMMMMNkc:cclllccccccccccccccc:.         ,ccc0MMMMMWXXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXo;;0MMMMMMMMMMKdddddxNWX0kxkOxdoxxxdddddddddd
MMMMMMMMMMMMMMMMMMMMMNkl;;:ccccc:cccccccccccc;,'...';:ccc;xMMMN0XXXNNKkXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKddddddKMMX0kdddxxxdxdddddddddd
MMMMWWNNNNNNNNNNNNNNNNNNKkdc;;::cccccccccccccccccccccc:;,cXWWWNNWMMWNNNNWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXddddddKMWXkdxxxddddddddddddddl
MMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xoc:,,;;;;:::::::;;;;,,;cxKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWxdddddk0kddxddddddddddddddddol
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNX0Okxdoooooooodxk0XWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKddddddddddddddddddddddddddlxX
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkddddddddddddddddddddddddcxWM

"""

camisa1 = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMKdlllloxNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMl''','''dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMNO,''''',':XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNK0OOOKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMKdc:c:;;.''''.''..':clocldXMMMMMMMMMMMMMMMMMMMMMMNXKK0OOkkkkkk0WMW0OO0KXxxc:lodddx;MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMx,,,'''''',,,'..',,'',,.',,;NMMMMMMMMMMMMMMMMMMMKlxOOO0XXXXXXXXOdxc:XK0l;ocOKxxxxdK:OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMX,,,,,,,,,,,,,,'.',,,,,,,,,,,xMMMMMMMMMMMMMMMMMMN:XXXXXXXXXXXXXXXXXO0XXc'ox,ol:MMXxdxkxxxxxkNMMMMMMMMMMMMMMMMMMMMMMMMMMNxoododoooooooddxkNMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMW:,,,,,,,,,,,,,,'.',,,,,,,,,,,:WMMMMMMMMMMMMMMMMW:0XXXxxXXXXXXXXXXoxXXXkkXdoOXkoOodKXXXXXXXXKoxMMMMMMMMMMMMMMMMMMMMMMMMOcO000000000000000kooKMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWl,,,'';,,,,,,,,'..,,,,,,,:,,,,,xMMMMMMMMMMMMMMMMlOXXXxo;dXXXXXXXKc0XXXXXXckXXX0:kXXXXXXX0kXXXXcKMMMMMMMMMMMMMMMMMMMMMMX;0000000000000000000OcxMMMMMMMMMMMMMMMM
MMMMMMMMMMMNc,,,',kMx,,,,,,,'.',,,,,,,No',,,,OMMMMMMMMMMMMMMoxXXXXXK,lkkxxxdO;0XXXXXXollKXXXkodxOKXXooXXXKd;oMMMMMMMMMMMMMMMMMMMMMMld000000000000000000000;XMMMMMMMMMMMMMMM
MMMMMMMMMMN:,''',0MMx,,,,,,,,',,,,,,,'0Wl,,,,,xMMMMMMMMMMMMx;xxxd0XcXMMMMMMW,OXXXXXXX;XXXXXxoMMN0;dodXXXXXXK,WMMMMMMMMMMMMMMMMMMMMM;O000000000000000000000odMMMMMMMMMMMMMMM
MMMMMMMMMMo,,'.'oMMMc,,,,,,,,,',,,,,,,dMW:,,,,'lXMMMMMMMMMX;0XWMO::xMMMMMMM0cXXXXXXXdoXXXXx;WMWXodK:XXXXXXXXokMMMMMMMMMMMMMMMMMMMMN;koc;'...'',;codk000000O:MMMMMMMMMMMMMMM
MMMMMMMMMMc,,,,',KM0',,,,,,,''.,,,,,,,:MMX,,,,,,,kMMMMMMMMX;K0xoc,KMMMMMMMMcOXXXXX0ocXXXXXXOodxk0XodXXXXXXXXKcMMMMMMMMMMMMMMMMMMMM,                 .';lxO0,WMMMMMMMMMMMMMM
MMMMMMMMMMx',,,,',0c,,,,,,,,''',,,,,,,,NMMd,,,,,,,OMMMMMMMMKdxOO;;MMMMMMMM0cXXXXXxlOdXXXXXXXXXXKxdo,lXXXXXXXXl0MMMMMMMMMMMMMMMMMMK                        ..kMMMMMMMMMMMMMM
MMMMMMMMMMMo,,,,,'''';;;;;',''',,;;;;,'0MMN;,,,,,,cWMMMMMMMMMMNNWMMMMMMMMOlXXXXXX;XXXXXXXXXXXXXKKXXc:kXXXXXXXK:XMMMMMMMMMMNNXKOkxc,;::cccccccccccc:::;;,,''.,kkkkkKWMMMMMMM
MMMMMMMMMMMWk;''..''';;;;;','',,,;;;;,'OMMMK:'','',KMMMMMMMMMMMMMMMMMMWkoxXXXXXXX;0XXXXXXXXXXXXXXXc0x:ddOXXXXXokMMMMMMKoollodxkO0000000000000000OkxxkkkkkkOOO0000OdldWMMMMM
MMMMMMMMMMMMMMN0dkd,',,,,,',';',',,,,,,NMMMMMXlcokNMMMMMMMMMMMMMMMMMMK:OXXXXXXXXK;dkXXXXXXXXXXXXXoxMW:XXXXXXXkcWMMMMMMN:O0kkkkkkkkkkkkkxxxkxkkxxkkO00000000000000000klMMMMM
MMMMMMMMMMMMMMMMMMMd:;,'',,;;:,''''',;oMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMd:odXXXXXXdoKXXXXXXXXXXXXXXxdMMMlOXXXXX0cWMMMMMMMMWxook000000000000000000000000000000000000000OlxMMMMM
MMMMMMMMMMMMMMMMMMMMNNNXNNNNXXXXXKXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMkoxlxXXKclkXXXXXXXXXXXXXXkoMMM0cXXXXXX:XMMMMMMMMMMMMNkxddodk00000000000000000000000000000OxoodXMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMklcdX:OKXXXXXXXXXXXXXXX;WMM0:oxXXXX0cMMMMMMMMMMMMMMMMMMWXOkkxxddooooloooddddooooodddxxxk0NMMMMMMMMM
MMMMMMMMMMMMMMMMMMOkkkkkkkkkkkkkkkkkkkOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNoco;ddxxxxxxxxxxxxxxo'MMMddclddxk:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXXXXXXNNWWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM0 ..',,;;;;;;;;;,'... XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKxkkkkkkkkkkkkkkkkkkNMMMM0xxONXcxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMk.',;, .'''...'. ,;,'.OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOkKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMo':,.  .''' ..'.  .,:.dMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNKK0OkkkkkkkkOOOkkkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMc....,:::::.:.:::,....cMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOOkxkO00KKKKK00OkkxxkkOdMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM,;:::::::::.:.:::::::,;MMMMMMMMMMMMMMMMMMMMMMMMWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdxkdxkkkkddxokok0KKodKK0oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMM'::::::::::.'':::::::;.MMMMMMMMMMMMMMMNK0OOOOOOOOOO0KWMMMMMMMMMMMMMMMMMMMMMMMMMKx00odKKKOkkxx00000Oox00K0kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMW.....':::::.::::::::::.WMMMMMMMMMMMK0OOKKKKKKKKKKKKKKxMMMMMMMMMMMMMMMMMMMMMMMMMKoK0kokO0xkKKOKKKKK0kOKKKKxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMX.::;;:::::.,.:::::::::.KMMMMMMMMNOx0KKKKKKKKKKKKKKKKKxXMMMMMMMMMMMMMMMMMMMMMMMMNlKKOkKKKKxKKkKKKKKK0kkOOOlNMMMMMMMMMMMN0OkxxxdddddxkOKWMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMO.:::::::::.N.:::::::::.OMMMMMMMMKk0kk0KKKKKKKKKKKKKKK0OWMMMMMMMMMMMMMMMMMMMMMMMMlOkO0KKKKk0KOKKKKKKKKKKKK0oMMMMMMMMMMMO.''''...........cXNWMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMd.::::::::'cMl'::::::::.xMMMMMMMMMNOOKkkOKKKKKKKKKKKKKKKOONMMMMMMMMMMMMMMMMMMMMMXlKKKKKKKKKk0KOKKKKKKKKKKKKkkMMMMMMMMMMW.::;;;;.'............;cdWMMMMMMMMMM
MMMMMMMMMMMMMMMMc'::::::::.KMK.::::::::'lMMMMMMMMMMMXO0K0kkOKKKKKKKKKKKKKKO0KKXNMMMMMMMMMMMMMMMMOkKKKKKKKKK0xkodxOKKKKKKKKKKdNMMMMMMMMMM,::::::.,;;;,,,,,,,,,;,:MMMMMMMMMMM
MMMMMMMMMMMMMMMM,,:::::::;,MMM,;:,.....,;MMMMMMMMMMMMMKOKKK0kOO0KKKKKKKKKKKKKKK0O0KNMMMMMMMMMMMMx0KKKKKKKKKKk0dd0OKKKKKKKKKKKoMMMMMMMMMMl,:::::.,:::::::::::::.XMMMMMMMMMMM
MMMMMMMMMMMMMMMM.;:::::::.dMMMd.::...'';'MMMMMMMMMMMMMMXk0KKKKKOk0KKKKKKKKKKKKKKKKKOO0KKXMMMMMMMxKKKKKKKKKKKOkkXoO0KKKKKKKK00OxMMMMMMMMMx':::::,'::::::::::::'dMMMMMMMMMMMM
MMMMMMMMMMMMMMMW.::::::::.XMMMN.::::::::.MMMMMMMMMMMMMMMO0KKKKKK0xKKKKKKKKKKKKKKKKKKKKdlloOKWMMMdK00KKKKKKK0kx0MxOk0000000kkOOXMMMMMMMMMO.:::::;.::::::::::::,WMMMMMMMMMMMM
MMMMMMMMMMMMMMMK.;;:::::,;MMMMM:,:::::::.NMMMMMMMMMMMMMMWkKKKKKKKOk0KKKKKKKKKKKKKKKKKolololxMMMMOkkkO00000OkdxKMNxxOO00KKKNMMMMMMMMMMMMMK.::::::.:::::::::::.kMMMMMMMMMMMMM
MMMMMMMMMMMMMMMO.'....::.OMMMMM0.:::::::.0MMMMMMMMMMMMMMMXkKKKKKKKKOOk0KKKKKKKKKKKKKololooxMMMMMMMMNXKKKKKXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMK.::::::.::::::::::;'MMMMMMMMMMMMMM
MMMMMMMMMMMMMMMd.,,,,;:;.MMMMMMM':::::::.xMMMMMMMMMMMMMMMMXkKKKKKKKKKKOkk0KKKKKKKKKllooolxMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNXK0l'::::::.::::::::::'dMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMl'::::::.oMMMMMMMo'::::::'oMMMMMMMMMMMMMMMMMWOOKKKKKKKKKKKOkkxO0KKKloooolkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXl:;,,,,,,,,;::::::::.::::::::::.0MMMMMMMMMMMMMM
MMMMMMMMMMMMMMM;;::::::.NMMMMMMMX.::::::,:MMMMMMMMMMMMMMMMMMMXO0KKKKKKK000kddxxx0olllolkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM;;::::::;'',',',',,'';::::::::::'xMMMMMMMMMMMMMM
MMMMMMMMMMMMMMM'::::::,;MMMMMMMMM,;:::::;'MMMMMMMMMMMMMMMMMMMMMKO0KKKK0OxoxxkkxONMN0dlkMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMl';;;::;.:::::::::::::::::::::::,cMMMMMMMMMMMMMM
MMMMMMMMMMMMMMM.::::::.kMMMMMMMMMk.::::::.MMMMMMMMMMMMMMMMMMMMMMWKO0KkddxkxkkKNMMMMMMWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOxol:;'.:::::::::::::::::::::::,lMMMMMMMMMMMMMM
MMMMMMMMMMMMMMN.''''''.WMMMMMMMMMW.,''''' XMMMMMMMMMMMMMMMMMMMMMMMMNOkkxxkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNl:,'.'',,,;;;;;;;;,,,''.'KMMMMMMMMMMMMMM
MMMMMMMMMMMMMMN;;;,'..lMMMMMMMMMMMl..',;:;NMMMMMMMMMMMMMMMMMMMMMMMMMMMKO0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXK0OkxxxxxxxxkOO0XNMMMMMMMMMMMMMMMM
"""

camisa2 = """
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
MWNWMWNWMNWMWNWMNNMWNWMWNWWNWMWNWMNNMWNWMWNWWNWMWNWMNNMW0dddl,:..,;xXMNWMWNWMWNMWNWMWNWMNWMWNWMNNMWNWMWNWWNWMW
NWMWNWMWNMWNWMWNWMNWMWNWMNNMWNWMWNWWNWMWNWMNNMWNWMWNWWK;             oKNNWMWNWMNWMWNWMWNMWNWMWNWMNWMWNWMNNMWNW
MWNWMWNWMNWMWNWMNNMWNWMWNWWNWMWNWMNNMWNWMWNWWNWMWNWMNx                .xKWNWMWNMWNWMWNWMNWMWNWMNNMWNWMWNWWNWMW
NWWWNWWWNWWNWWWNWWNWWWNWWWWWWNWWWNWWNWWWNWWWWWWNWWWNWc                 .,WWWNWWNWWWNWWWNWWNWWWNWWNWWWNWWWWWWNW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW. ..''....          xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK  ,,,,,,,,,,,,,,    .WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0 ',,,,,,,,,,,,,,.    KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWNWWWNWWNWWWNWWWNWWNWWWNWWNWWWNWWWWWWNWWWNWWNWWWNWNd.'..',,,,,,,,,,,.   kNWWWNWWNWWWNWWNWWWNWWWNWWNWWWNWWNWWW
NWMWNWMWNMWNWMWNWMNWMWNWMNNMWNWMWNWWNWMWNWMNNMWNWMWc.'.',...,'.....,,.  lWMWNWMNWMWNWMWNMWNWMWNWMNWMWNWMNNMWNW
MWNWMWNWMNWMWNWMNNMWNWMWNWWNWMWNWMNNMWNWMWNWWNWMWNWo.,,,,;,',''c.;..,  .KWNWMWNMWNWMWNWMNWMWNWMNNMWNWMWNWWNWMW
NWMWNWMWNMWNWMWNWMNWMWNWMNNMWNWMWNWWNWMWNWMNNMWNWMWO,,,,,,',,,,,,,,,,.,,kWMWNWMNWMWNWMWNMWNWMWNWMNWMWNWMNNMWNW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW:,,,,.,,,,,,,,,,,',oWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW;,,,,,,'',,,,,,,,ckWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWc,,,'.''',,,,,,,kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX',,,,',,,,,,,,;WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
NWMWNWMWNMWNWMWNWMNWMWNWMNNMWNWMWNWWNWMWNWMNNMWNWMWNX',,,,,,,,,,,,,kWNMWNWMWNWMNWMWNWMWNMWNWMWNWMNWMWNWMNNMWNW
MWNWMWNWMNWMWNWMNNMWNWMWNWWNWMWNWMNNMWNWMWNWWNWMWNWMk,,,,,,,,,,,,,'oWMNWMWNWMWNMWNWMWNWMNWMWNWMNNMWNWMWNWWNWMW
NWMWNWMWNMWNWMWNWMNWMWNWMNNMWNWMWNWWNWMWNWMNNMWNWMNOc,,,,,,,,,,,,,,':kNWNWMWNWMNWMWNWMWNMWNWMWNWMNWMWNWMNNMWNW
WWNWWWNWWNWWWNWWWNWWNWWWNWWNWWWNWWWWWWNWWWNWWNWNxc,,',,,,,,,,,,,,,,,,,',lONWWWNWWNWWWNWWNWWWNWWWNWWNWWWNWWNWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX00kxl,..',,,,,,,,,,,,,,,,,,,'....'xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNkdc;,,,,'...',,,,,,,,,,,,,,,,,,,.....',,:xNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO;,,,,,,,....',,,,,,,,,,,,,,,,,,'.....',,,,,;lkXWWWWWWWWWWWWWWWWWWWWWWWWWWWW
NWWWNWWWNWWNWWWNWWNWWWNWWWWWWNWWNo,,,,,,,'.....,,,,,,,,,,,,,,,,,,......',,,,,,,,,,:0WWWNWWNWWWNWWNWWWNWWWWWWNW
MWNWMWNWMNWMWNWMNNMWNWMWNWWNWMWNc,,,,,,,'......',,,,,,,,,,,,,,,'......',,,,,,,,,,,,;WNWMNWMWNWMNNMWNWMWNWWNWMW
NWMWNWMWNMWNWMWNWMNWMWNWMNNMWNWk,,,,,,,,........',,,,,,,,,,,,'.......',,,,,,,,,,,,,,kMWNMWNWMWNWMNWMWNWMNNMWNW
MWNWMWNWMNWMWNWMNNMWNWMWNWWNWMWc,,,,,,,............''','''...........,,,,,,,,,,,,,,,;NWMNWMWNWMNNMWNWMWNWWNWMW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW,,,,,,,,..............................,,,,,,,,,,,,,,,,0WWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd,,,,,,,,'.............................',,,,,,,,,,,,,,,dWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWW0c,,,,,,,,,...............................,,,,,,,,,,,,,,,kWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWNl,,,,,,,,,,,...............................,,,,,,,,,,,,,,cWWWWWWWWWWWWWWWWWWWWWWWWW
MWNWMWNWMNWMWNWMNNMWNWMWNWc,,,,,,,,,,,,..............................',,,,,,,,,,,,,,XNWMNWMWNWMNNMWNWMWNWWNWMW
NWMWNWMWNMWNWMWNWMNWMWNWMx,,,,,,,,,,'',,'...........................',,,,,,,,,,,,,,cWMWNMWNWMWNWMNWMWNWMNNMWNW
MWNWMWNWMNWMWNWMNNMWNWMWNo,,,,'',''',,,,,,'...................'''''.,,,,,,,,,,,,,,,kWNWMNWMWNWMNNMWNWMWNWWNWMW
NWWWNWWWNWWNWWWNWWNWWWNWN,,,,,,,,,,,,',,,,''.'.'''''',,,,,,,,,,,,,,',,,,,,,,,,,,,,,0WWWNWWNWWWNWWNWWWNWWWWWWNW
WWWWWWWWWWWWWWWWWWWWWWWWd,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',,,,,,,,,,,,,,,WWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWW:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,''',,,,,,,,,,,,,,xWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWW:,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,',',',,',',,,,,,,,,,,,,,,,cWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWNWWWNWWNWWWNWWWNWWNWWWd,,,,,,,,,,,,,,,,,,,,,,,,,,''',,,,,,,,,,,,,,,,,,,,,,,,,,,XWWWNWWNWWWNWWWNWWNWWWNWWNWWW
NWMWNWMWNMWNWMWNWMNWMWNWWl,,,,,,,,,,,,,,,,,,,,'','',,,,,,,,,,,,,,,,,,,,,,,,,,,,,OMWNWMWNMWNWMWNWMNWMWNWMNNMWNW
MWNWMWNWMNWMWNWMNNMWNWMWNW0kkkxddolc:::;'''....',,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,dWNWMWNWMNWMWNWMNNMWNWMWNWWNWMW
NWMWNWMWNMWNWMWNWMNWMWNWMNNMWNWMWNWWNWMd..........'',,,,,,,,,,,,,,,,,,,,,,,,,,lNWMWNWMWNMWNWMWNWMNWMWNWMNNMWNW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW,...............'',,,,,,,,,,,,,,,,,,,,cNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWX......................'''''',,,,,,,,;xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx...............................',lx0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWc................................,WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW,................................,WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW

"""

frutas1 = """
cccccccccccccccccclllcclolccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccdOK0occccccccccccc
cccccccccccclOKKXNNNNNKNNN0xlccccccccccccccccccccccccoOKKklccccccccccccccccccccccccccccccccccdWXdWOccccccccccccc
cccccccccccclNNkkxdddx00x0KXWKOoccccccccccccccccccclxNW0KWOxkdcccccccccccccccccccccccccccccccoNWxWNOoccccccccccc
cccccccccccccdNN0kkO0KKkKOddkXWKcccccccccccccccclkOXWKXNOWXKXWOlccccccccccccccccccccccccccco0WNXX0KXW0lccccccccc
cccccccccccccclOWWX0kdoooxkOXWXlccccccccccccccccOWN00kdxkxdx0KWNlccccccccccccccccccccccclxKWNXXXXK0OKWKccccccccc
cccccccccccccl0WKkdoooooooolldXNdccccccccccccccckWKxc:cllllcckNNlccccccccccodxxdddooddk0NWNXXXXXXK00OKWkcccccccc
ccccccccccccc0WkOxoooooooooolclXWocccccccccccccOWd,;,,,,,,,,,';NXccccccccc0NKNNNNWWWWNNNXXXKXXXXK0O0O0WKcccccccc
ccccccccccccdW0kkoooooooooooolcoWXcccccccccccccXN;,:,c,::,c,,'.0WlccccccccXWO0KKKKKKKKKKKKKXXXXXK0O0O0W0cccccccc
cccccccccccckWOkxoooooooooooolccNNccccccccccccc0Wc;c,;c,,c:,,';WKcccccccccoNWKO000000KKKXXXKKXXK000OONWocccccccc
ccccccccccccdW0odooooooooooooccxW0cccccccccccccoNK:,l,,c;:,,''0NlcccccccccclkXN0OKKKXXKKKKKXXKK000O0XWxccccccccc
ccccccccccccc0WkoooooooooooolcdNXlccccccccccccccoXNo,;l,::,':KNocccccccccccccoNXO00000KKXXXKK0000OKNXdcccccccccc
ccccccccccccclOWKkooooooolllxKW0lcccccccccccccccclkNXxc;:,cON0lcccccccccccccccl0NNX0kKKKK000000OKNNklccccccccccc
cccccccccccccccokKNXK0000KXNKklcccccccccccccccccccccdOKXKX0klcccccccccccccccccccldONXK0000000KXNKklccccccccccccc
ccccccccccccccccccclddxxddlcccccccccccccccccccccccccccccccccccccccccccccccccccccccclk0XXNNNXKOxlcccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccclkOkdoclddlccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccckWXKXNNW0WXcccccccccccccccccccccccccccccldx00kcccccccccccccccc
ccccccccccccccccclxO000kocccccccccccccccccccccccccoNNOxxOkKW0ccccccccccccccccccccccokkdoONWNX0NWdccccccccccccccc
cccccccccccccldkKWX0OO0XWNNNXOdlccccccccccccccccccl0WWNK0XNNkcccccccccccccccccccccoWXkKWNkdddxNNlccccccccccccccc
ccccccccccccc0WNOxoooodllOkk0XWNoccccccccccccccccc0WX00000OXWkcccccccccccccccccldOKWWW0xxkO0KWWKxlcccccccccccccc
cccccccccccccdKWX0kkOdxXOkWXXWNOcccccccccccccccccdWWK00000OkNNlcccccccccccccccxNNkdo::ldo0xoccldKNOlcccccccccccc
cccccccccccccccokKWWxKMMWoNWX0xlcccccccccccccccclKWX0000000O0WXocccccccccccccOWO:dc,,,,,,,,,,,'''cNXoccccccccccc
ccccccccccccccoOKNWoKWMWKkcOOOXWxccccccccccccccoNWXK00000000OOXWkccccccccccclWX;kc,,,,,,,,,,,,,'''lW0ccccccccccc
cccccccccccccxWXxol;::odl;,,,,;NWoccccccccccccoNWKXK000000000OkXWxccccccccccdWO,k,,,,,,,,,,,,,,''';WXccccccccccc
cccccccccccccXWol,,,,,,;,,,,,,'OWxccccccccccccOWXXX00000000000kOWKcccccccccclNN;l,,,,,,,,,,,,,,'''lW0ccccccccccc
ccccccccccccc0Wd;,,,,,'c;,,,,,lNNlccccccccccccOWXXN00000000000k0W0ccccccccccckWO;,,,,,,,,,,,,,''';XNoccccccccccc
cccccccccccccoXWkl:::lOWN0kkOXW0occcccccccccccdWWKNK000000000kkNWdcccccccccccckWKl,,,,,,,,,,''',dNXocccccccccccc
cccccccccccccclx0XXXXKOdoxxxxolccccccccccccccccxNNXXXK000000kOXWxccccccccccccccoONXkdl::;;:clx0NKxcccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccco0WWNXXKK00KNW0occccccccccccccccccokOKXXXXXK0kdlcccccccccccccccc
ccccccccccccccccccclolcccccccccccccccccccccccccccclxk0KKXK0Oxlcccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccl0WNNKxlccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
ccccccccccccccccclNW0O0WNkdlccccccccccccccccccccccccccccccooccccccccccccccccccccccclolccccldkxkkkdcccccccccccccc
ccccccccccccccccccoXWWKkKXWNOlcccccccccccccccccccccdxdlcxXWWKcccccccccccccccclxO000NWWX0xkNWXNKKWWOccccccccccccc
cccccccccccccccccc0WXxddddx0WNdcccccccccccccccccccxWWNNNNKNWW0lcccccccccccccxNWX000K0kOKNWKdoooOWNoccccccccccccc
cccccccccccccccccdWWl;dl:od:oWWoccccccccccccccclk0WWWXkkdOKNWWKkocccccccccccdXWW0xxxxxxxxkocccoNWNlccccccccccccc
cccccccccccccccccoWW;.,'',;''OWOccccccccccccccOWKxdlloc;;loc::l0W0lcccccccccccoNWXkxxxdlllo::::kKXWKoccccccccccc
cccccccccccccccccoWW;'''''''.'NWocccccccccccc0Wkldc;,;;;;;,;;;''lNXlccccccccccc0WWXOxdo:::c:;;;;::oWNlcccccccccc
ccccccccccccccccckW0:;'''''''.xWOcccccccccccdWK:O:;;;;;;;;;;;;,''xWxccccccccccccldKWNkc;;;;;;;c::;cNWocccccccccc
cccccccccccccccckWX:l''''''''.cWKcccccccccccxWOcx;;;;;;;;;;;;;,''dWkccccccccccccccxWKo::;;c:::,;;:KW0ccccccccccc
cccccccccccccclKWO:c,''''''''.;MNcccccccccccdWK:o;;;;;;;;;;;;;,''0WdcccccccccccccclXWkl:::;;;:c:::oWKccccccccccc
ccccccccccccclXWd','''''''''..:MXcccccccccccc0Wx:;;;;;;;;;;;;,''xWOcccccccccccccccclkXWWKl::;;:;;oXWxccccccccccc
cccccccccccccxW0'''''''''''...oW0cccccccccccclKWk:;;;;;;;;;;,,oKWkcccccccccccccccccccclOWNOkl:::;OWkcccccccccccc
cccccccccccccxM0..''''''.....;NWoccccccccccccccxKNKOxxddddxkKNKklcccccccccccccccccccccccldKW0oclxNNlcccccccccccc
ccccccccccccclXWx'.........,xWNdcccccccccccccccccldxkO000Okxdlcccccccccccccccccccccccccccccx0XNNKklccccccccccccc
cccccccccccccclkNW0xolcloxKWXkcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccoxkO000Okdlcccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

"""

frutas2 = """"
MMMMMMMMMMMM0cxKNNX0xoooodoxXMMMMMMMMM0;;xMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMM0;xdoolodxxxxkOkkOkNMMMMXl,;doMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMWx,ooooooooooooookXkOMMd,;llOWMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWx,looooooooooooooXd0c,lokWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMO;:ooooooooooooo0x.,ooNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNx::looooooooodk.,dxMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMW0oc:cloooccxk'doMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNKOkOOkOOl'ld0KNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMW0xdodkOc,:kOkxkOOONMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMXxldOOOOOOc;:ckOOOO0XOxXMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNkcdOOOOOOOOOOOOOOOOOOO0WkkMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMXx:kOOOOOOOOOOOOOOOOOOOOO0WOkMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMXx:kOOOOOOOOOOOOOOOOOOOOOOOKMoNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMNO:kkkkOOOOOOOOOOOOOOOOOOOOOONKdMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMM0ocOdoodkOOOOOOOOOOOOOOOOOOOOKMlMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMXk;kkooooxOOOOOOOOOOOOOOOOOOOOOWx0MMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMWOloOxooooxOOOOOOOOOOOOOOOOOOOOOXWoMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMXk:OOdooooxOOOOOOOOOOOOOOOOOOOOO0WkOMMMMMMMMMMMMMMM
MMMMMMMMMMMMMNO:xOxoooodOOOOOOOOOOOOOOOOOOOOOOO0WdKMMMMMMMMMMMMMM
MMMMMMMMMMMMWOcoOkdooookOOOOOOOOOOOOOOOOOOOOOOOO0WxOMMMMMMMMMMMMM
MMMMMMMMMMMW0llOkdooooxOOOOOOOOOOOOOOOOOOOOOOOOOO0N0dWMMMMMMMMMMM
MMMMMMMMMMW0llOOdoooodOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXNx0MMMMMMMMMM
MMMMMMMMMW0loOkdoooodkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0N0xXMMMMMMMM
MMMMMMMMWOcdOkdoooodkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0NkxWMMMMMM
MMMMMMMNk:xOxooooodkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXdKMMMMM
MMMMMMXx:kkdooooookOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0NOxWMMM
MMMMMKockkdooooookOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXdWMM
MMMW0olOkdooooooxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXoWM
MMW0olOkdoooooodkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONKxM
MW0dcOOdoooooookOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOWdX
MKk:kOxooooooodOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXXo
NOcoOOdoooooooxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0Ml
KO;OOkooooooookOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOWl
Ok;OOxooooooookOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONl
Ok;OOxooooooodOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOWl
Ok;OOkooooooodOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOWl
0O:xOOdoooooodOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0Xo
NOxcOOkdoooooxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXdX
MKOloOOkxooodkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONdM
MW0kcoOOOOkkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOXoNM
MMMKOolkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOKdXMM
MMMMXOdcdOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO0oXMMM
MMMMMWKOoldOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOxkWMMMM
MMMMMMMWX0dllxOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkdxNMMMMMM
MMMMMMMMMMNKOdlodkOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOkodOWMMMMMMMM
MMMMMMMMMMMMMWNKkoooodkOOOOOOOOOOOOOOOOOOOOOOOOkddxk0WMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWNXOdooooooodxxxkkkxxddoodxxkOXMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMWNXK0xol::;::cldOXWMMMMMMMMMMMMMMMMMMMMMM

"""

ave1 = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX0WWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWkldWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKlkWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkllcXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWOocOMMMMWNMMMMMMMMMMMMMMMMMMMMMMMMXkolcoWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOdlcxMMWNkoWMMMMMMMMMMMMMMMMMMMMMWKxoll:OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMWNXXXKKK00OxddlccOK0kocdWMMMMMMMMMMMMMMMMMMMWNOdllc:dWMMMMMMMMMMMMMMMMMMMMMMMMMXOxOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWNX0Okxxdddooolllllllloool:oXMMNXMMMMMMMMMMMMMMMXOxollc:dNMMMMMMMMMMMMMMMMMMMMMMMMXd:::;OMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMWXXKKXK000KK0Okxlllllllllllc:dXXKOlKMMMMMMMMMMMMMNkdolllc:xNNWMMMMMMMMMMMMMMMMMMMMMW0c:::;;kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWXKXXXK0KNWWK0NWK00dllllllllllllooockMMMMMMMMMMMMXkolllllc;:l::c0MMMMMMMMMMMMMMMMMMMNkc::::;:XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMNXXKK000O0XXXX0ON0llo:;cNNOXKxlllllllllcc:;c0WMMMMMMMMMWKklllllllc::::;;;OMMMMMMMMMMMMMMMMMXxc:::::;:0MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
WNKOkkxxddddxXXXXKON0;,.  ,lWKKXXOlllllllllllc::cOWMMMMMMN0xollllllllllllc;cOWMMMMMMMMMMMMMMMWOl:::::;;,;lkNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
0xxddddddddd0XXXKOOWO;,:d;dXKKXXKOlllllllllllllc:;xWMMWN0xdllllllllllllccoONMMMMMMMMMMMMMMMW0o::::::;;,;;;;xMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
XK0OxooooooxKXXXKKKXXKOO0KXKXXXK0dllllllllllllllc:;xWX0xdllllllllllllc::ldx0WWMMMMMMMMMMMWKdc:::::;;;;;;;;;kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMWNN0xolkXKXXXXXXXXK000KXXXXKxddlllllllllllllll:::dxdlllllllllllllllllc:;;xWMMMMMMMMWNOdc:::::;;;;::;;;;oWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMNOxxxlkXXXXXXXXXXXXKKXKK0Okxdollllllllllllllll::::cllllllllllllllllllc:;c0WMMMMMMWXOoc:::::;;;;:::;;;:kWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMWO00xooKXXXXXXXXXKKK0kddxxddolllllllllllllllll:;;;:;clllllllllllllllcclx0NMMMMMNK0xl:;;:::;;;:::::;;lONMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMWKdoddoKXXXXXXXXXXXXKKKOxxxollllllllllllllllc::::::::cllllllllllllc:;lkWWMMWXKkdlc:;;;;;;;;::::::;;lkKWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMWW0xolxKXXXXXXXXXXXXXXXK0xxdlllllllllllllllclllllllllcclllllllllllc;;lKX0kdoc::::;;;::;;;:::::;::;;;;xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMWX0O0KXXXXXXXXXXXXXXXKkollllllllllllllllllllllloooollcllllllcccclollc:;:::;;;;::::;;,;::::::::;;;lWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMNOO0KXXXXXXXXXXXXXXKklllllllllllllllllllllllccllodolcccccccc:ccclllc;;;:::::::;;;;::::::::;;;;OWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMWKOO0KKKXXXXXXXXXXXKxlllllllllllllllloolllllccccccccccccccllllllllc;:::::;;;;;;:::::::::;;:xXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMWX0OOO000KKKKKKKKK0dlllllllllloddddolccccccccccclllllllc:cccllc::;;;;;;;:::::::::::::lx0NNNNNNNNNMMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMWXK00OOkkkkkOKKK0olllllcoxkxoc::cclllloolllllll::ll:;;;;;;;::::::::;,,;::;;;;;:dk0NMWKKKXXXXXXWMWWWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMWNX0O0KXXXKxlllllkkdol::lloooolllclllllcc;;:::::::c:;:c::cc::;;,,::,;::;;:lxXMWKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMN0KXXXX0ollokoooc;clllllllolc;:c::;;:;;c:c::::;,;::::;;;;,,;:::;;:;;;;,:XMWKKXXXXXXNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMW0XXXXKdlcxoloo::llollc:cc:;;:lc:::c,;cc:;;:::;;;:::cc::::;:c:;;;;;;,c0MMWKKXNNNNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMN0XXXXOllollol::lllolc:::;;:ccc:::c;,::;;:::;;;;:::::::c:;;::,,;;lkO0KWMWKKNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMKKXXXKollllol::clllc::ccc::ccc:::c;,::,,,,,;;;:::;;;;;;,,;;lodONMMWK0XMWK0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0XXXXk:llllllc:;::::cccc::;::::::;;::::::::::c::::::::;;;;cOKNMMMMWWWMMWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMK0XXXKl:lllllllc::::::::;;;;;;;;;;::::::::::;:::::::;;;;;;:ddxO0KXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWO0XXKx::llllllllc:;;;;;;;::;:::::::;;::::::;;,;;;;;;;;;;clllloxxxkO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKO0KXKl;:clllllllll:;:::::::;;:::::;;;;;;;;;;;:cc::::ccllllllllllodxxxO00O0KKKKKKKKKKKKKKXXNNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNkO0KXOc;;:cllllllllc::::::;;;;;;;;;;;:c::;;;:clllllllllllllllllllllllodxxxkxdoodddxxxxxxxxxxxkOO000KKKXNWMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXkOO0KOl;:;::cllllllllc::;;::clcc::cllllllllllllccccccccccclllllllllllllllodxxxddolccccccccccclloodddxddxxkO0KXNWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOOO0KKx:;;;:::cll:clllllllllllllllllll::cclllll:;;;;;;;;;;::::::ccccclllllllllodxdool:;;;;;;;;;:::::::cccclllldkOKNMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOOOO00Oo:;;;;;::;;:clllllllllllllllllc;;;::cc::;;;;;;;;;;;;;;;:::;;;;:::::cccllllloddoooxkOKKKK000OOkkxddolcc::::cox0NMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNOOOOOO0ko:;;;;;;;;;lolllllllllllllllc;;;;;;;;;;;;;;;;;;;;;:cloxxxdolc:;;;:;;;:::cclllllooodk0XWMMMMMMMMMMMWWNK0Okdolo0MMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKOOOOOOOkxoc:;;;;;;lollllllllllllllc;;coc:;;;;::cloxxk0KXNMMMMMMMMMWNXK0Okxdoc:;;:::ccclllllloxOKNWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXKOOOkdkOOOxdllc:;colllllllllllll:::cOOkkO0KNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXK0Oxdlc::::ccllllldxOKNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNooddodxkkOOOOOkxxdllllllllllc:;;;cKNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kxol:::cccllloxOXWMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWdddocoddooddxxxxxddlc::::::;;;;::xWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0Oxol::::::cdk0NMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXxolddddollooddoooodddolc:::::::cOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0Oxol:;;:lx0NWMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXOoddlloooooooloolldolooloddoollXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWX0kxoc:lxKW
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNKxodddolloddddddodddddddddddocOWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNXKO0
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNooodlooddoooodddoooddddddddkNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMKdddloddddoxkxxkOXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0xkxdddddkWWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNKOxkk0NMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXX00WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

"""

ave2 = """
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXXXXNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0KNNNN0k0NNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMo...'NNXOx0NNNNNXWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMX,. ..0NKl;dNNNNNXXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWKkkd,  NNNXKNNNNNNKKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN0kkkkxxc.OXNNNNNNNXK0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0kxxxxddxkO0KNNXXX0K0000WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXXNNWMMMMMMMMMMNNNX00XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNN0KMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNKKMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNX0XMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNNNNNXKWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWWNNNXXXKKXNNNNNNKxOOOOOkkkkkkkkkkkkkkkkkkkkkkkkkkOkkkkkkOOOOOOOOO000000KKKKKKXXXXXNNNNWWMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMWNXXK0OOkkxxddoooooooood0NNNNNN0dooooooooooooooooooooooooooooooodddooooooooooooooooooooooooooooooooooooooddxkO0XNMMMMMMMMMMMM
MMMMMMMMMMMWXKOkxdooooooooooooooooooooooxXNNNNNNOoooooooooooooooooooddddooooooooooooooooooooooooooooooooooooooooooooooooooooooooooodk0NMMMMMMMM
MMMMMMMMNOxooooooooooooooooooooooooooooxNNNNNNN0oooooooooooodkO0KXNNNNNNNNXXK00kxdoooooooooooooooooooooooooooooooooooooooooooooooooooooxXMMMMMM
MMMMMMWkdooooooooooooooooooooooooooooodNNNNNNNNdoooooooodk0XNNNNNNNNNNNNNNNNNNXNNNKdlooooooooooooooooooooooooooooooooooooooooooooooooooooOMMMMM
MMMMMMKdooooooooooooooooooooooooooooooKNNNNNNNNoooooookKNNNNNNNNNNNNNNNNNNKXXXXNK0xdooooooloooooooooooooooooddooooooooooooooooooooooooooooKMMMM
MMMMMMNdooooooooooxkOkxdooooooooooooodNNNNNNNNNOooookXNNNNNNNNNNNNNNNNXXXKKNNX0kxollllllllllooooxkOxoooooodddooooooooooooooooooooooooooooo0MMMM
MMMMMMMNdoooooodxK0xkKKKdooooooooooookNNNNNNNNNNNXXNNNNNNNNNNNNNNNXXXXKNNNX0xdlllllllloO000O00KXK0kdddddxxxxdxxxxxxdddxxxddddddooooooooooxWMMMM
MMMMMMMMWkooodddkKOoxKK0dooooooooooookNNNNNNNNNNNNNNNNNNNNXXNNNNNNNKNNNNKxollllllloxKNNNNNNNNNX0kxxxddddddooooooooooooooooooooooooooooooOWMMMMM
MMMMMMMMMMKdooooodxkOOOdooooooooooooooKNNNNNNNNNNNNNNNNNNNNXXXNNNNNNNKxolllccloxKNNNNNNNNNXX0OxddddxxxdoxO000kdddddoooodddddddddooooox0NMMMMMMM
MMMMMMMMMMMWkoooooooK0xooooooooooooooookXNNNNNNNNNNNNNNNNNNNNNXXXXXXKOxkkOKXNNNNNNNNNNNNXKkxxdddddoxxkkxKkck0KOddddooooooooooooxO0KXWMMMMMMMMMM
MMMMMMMMMMMMMkoooookKKooooooooooooooooodxO0KXNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXXKK0Odoooooooooooodd0KO0KKOoooooooooooooooOMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMKoooodKKKOOO000OkkddxlooodxxkkkkOO0KKXXXXXNNNNNNNNNNNNNNNNXXXXXXKKKK00Okkxdooooooooooooooooodxx0KOooooooooooooooood0NMMMMMMMMMMMMM
MMMMMMMMMMMXkooooo0KKKKKKKKKK0kK0xddddddoooodxxkkkkkOOOOOO0000000000000OOOOOOOkkddddooooooooooooooooooooooookKKOdoooddddoooodoooood0NMMMMMMMMMM
MMMMMMMMXOdoooooook0KKKKKKK00O0OxdooooooooooooooooodxxxxxkkkkkkkkkkkkxxxdddxxxxxxxxxxdxxxddddddoooooooooooooxKKKKOOKK0KKK0OOKOdooooooxKWMMMMMMM
MMMMMNOdooooooooooxkkkkOOOOOkkkxdddooooooooodkOOkxoooooooooodddddddxkkkkxxxddooxxxdodooodddddddddddddddddooodKKKKKKKKK0O0KKKKxxxddddooooOWMMMMM
MMWKxooooooooooodddoodddxxxxkxxddddddddddood00KKKKdooddooodddooooooooodddxxkkkKkx0K0kkxxxxxdoooooooooooooooooxO00KKK00OO0KK0xoooooooooooooOWMMM
M0dooooooooooooooooooooooooooooooodddddddoodoc0OkxdoddddddddoooooooooooooooddOKkoOKKxdooddxxxxxxkxxxxdooooooodxxxxkkOOOOOkkdddooooooooooooodXMM
kooooooooooooooooooooooooooooooooooooooooooookOxdxkdodxkOkooooooooooooooooooooxO000Odoooooooooooooooddddddoooddddddddxxxxxxxxxxdddddooooooooo0M
dooooooooooooooooooooooooooooooooooooooooooooxKKdkOOKK0KK0dooooddooooooooooooooxK0koooooooooooooooooooooooooooooooooooooooooooodooooooooooooooK
W0xoooooooooooooooooooooooooooooooooooooooddoOKKKKKK000kOKxoddddddddddooooooood0KKdoooooooooooooooooooooooooooooooooooooooooooooooooooooooooood
MMMWX0kxdoooooooooooooooooooooooooooooooodddoKKKKKKKKK0O0OdoooooooooooooooodddxKKKOkOO0000OkkOddddddddooooooodddddoooooodddoooooooooooooooooooo
MMMMMMMMMWNXK00OkxxdooooooooooooooooooodddoooOKKKKKK00OkkdddooooddxddoooooooooOKKKKKKK00000KKxdddddooooooooooodoooooooooooooooooooooooooooooooK
MMMMMMMMMMMMMMMMMMMMMWNXK0OxdoooooooodddoooooddxxxxkkkxxdooooooooooooooooooooodOKKKK00KK0O0KOoooooooooooooooooooooooooooooooooooooooooooooookNM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNX0kxddoooooooooooooooooooddddddddooddddddoooooodxxkkOOOOOOOkkxddddxddddddoooooooddddoooooooooooooooooooodkOXWMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWXOooooooooooooooooooooooooooooooooooooooooooooooddxxxdxxxdddddddddddoooooooooooooooodddxxxkkO00KXNWMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooodddoooooookXNNWWWWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMW0ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooodddoooooooood0WMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNXKOxooooooooooooooooooooooooooooooooooooooooooooooooooooooooooddddooooooooooooooxKWMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM0dooooooooooooooooooooooooooodddoooooooooooooooooooooooooooooooddoooooooooooooooooooookXMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMWooooooooooooooooooooooooooodddoooooooooooooooooooooooooooooooooddoooooooooooooooooooooooxKMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXdooooooooooooooooooooooodddooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooookMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMXOxooooooooooooooooododooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooNMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNK0kxdooooooooodddooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooxONMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNXXK00OOkkxxdddoooooooooooooooooooooooooooooooooooooooooooooooooodxxkO0XNWMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMWNNXXK00OOOkkkxxxddddoooooooooooddddxxxkkO00KXNWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

"""

tiempo1 = """
OKKXXXXXKXXXXXXXXXXXXXXXXXXXXXXXXXX'                                      ;dkO000000KXKXKOXXXXXXXXXXXXXXx:XXllXXXXXXXX.KXKdclKXXXXXXXXOc.xXXXXXXXXXXKXXXXXK0xol:;cc,                                         
OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0,                                    ':okO000K0KKKXXXXXKlckKO0XXXXXXX0;0XK'0XXXXXXX0.XllokKKXXXXXXXXXXx;XXXXXXXXXXXXXKKXKKK0kdlc:c:,.                                      
0XXXXK0XXXXXXXXXXXXXXXXXXXXXXXXXK.                                  .;dkO000KKKXXXXXXXXX0ollodxxcXXXXXX00XXcdXXXXXXXXKxKoxxxxOXXXXXXXXXXX,kXXXXXXXXXXOxxkKkkXXKK0Oxoc::;'.       ...                         
0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'                                 .cxO0000K0kXX0XXXXXXXXoO;xXXX0'KXXXXXXXKKOKKXXXXNNXNXXXXXXXXXXXXXXXXXXX0OXXXXXXXXXllkOl:XXXXKXXKKKOdlc;:;'.     .:xd'                      
0KXOdOXXXXXXXXXXXloXXXXXXXXXXXXc                                .lk000KKXKXXKddxdxXXXXXXXX:xOkl.:l:;,......  ......,;:ldxOKXXXXXXXXXXXXXXXXXXXXXXXXXoOXKcoXXXXXXKKXXKK0koc:;:,.      'do.                    
OKKd:xXKKKKXXXXXXo.KXXXXXXXXXXx                               ,ok0KKKKXKXXXdxddxldXXXXKX0xc.                              ..,cokKXXXXXXXXXXXXXXXXXXXXXK,lOdoKXXXXXXXKXXKKOxlc;:;'      .,.                   
OKKXXXXo:cccccld00.dXXXXXXXXXK.                             'oOKKKKKXXXXXXX0dxolOXXXKd;.                                        .,cdOXXXXXXXXXXXXXXXXX0'coOXXXXXXXXXXXXKXXK0kocclc.       .                  
OK0KXXXXXXXX0Oxl;;.;XXXXXXXXXl                             :kKKKXdKXXXXXXXXXXXXXXKx:.                                                'l0XXXXXXXXXXXXXXXKXXXXXXXXXXX0doxXXooKK0xlccc;.       .                
0XXXXXXXXXXXXXXXXOloXXXXXXXXK.                           .o0KKXKXkdxoxdKXXXXXXXk:.                                                      ,o0NXXXXXXXXXXXXXXXXXXXXXXxckO,dkk0KKKKOdlccc;.      ..              
0KXXXXKXXXXXXXXXXXXXXXXXXXXXl                           'kKKXKXXXck0,xckXXXXKo'                                                            ,d0XXXXXXXXXXXXXXXXXXXXddXOoxd;dXKKXKKOolllc'      .;:            
00XXXKdodxkOO000KKXXXXXXXXXX.                          :OKKXKXXXX0dxdOOXXXKo.                                                                 ,dXXXXXXXXXXXXXXXXXXXXXO00x;xXXXXKXKKkolol;.      lk'          
0XXXXK0kxdolc::;:cldxO000KKd                         .lKXXKKXXXXXXXXXXXXKo.                                                                     .oKXXXXXXXXXXXXXXXXXXxodxKXXXXXXXKXKKkool:.      :K:         
kKXXXKKKXKXXKK0Oxoc;,,,,;;c.                        .xKKKOKXXXXXKXXXXXXx.                       .....''''''.....                                  .oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0dccc;      'kc        
0XXXXXXXXXXXXXXKKKKKKOxoc,.                        .xKKKKK0ddOX0cXXXXXo                    .';cdkOOO000000000OOkxoc,..                              'OXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKXX0dcclc      .c,       
OXXXXXXXXXXXXXXXXXXXXKKKK0k                        lKKKKKXXKOkxocXXXXl                 .;lx000KKK0OKXXXXXdKXXXXKK0KKOkxl;..                           lKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKK0xcll:.      ..      
OXXXKOxddxkKXXXXXXXXkk0XXXx                       '0KXKKX0kk0KXK0XXXc               .:x0KK0OO0XXKxlOkXXXOOd0XX0oOOxXXXXX0Okd:..                        .cXNXXXXXXXXXXXXXXXXXX0:oOXXXXOoKKKklccc.      .      
OXKc:cl:..:;:OXXXXXXOOXXXXo                       oKKKKKXXKOxddox0Ko             .:d00KXXXkokkXK0ool:dxxxkkXXXOkxx0XXXKd0XXXKOd:..                       .OXXXXXXXXXXXXXXXXXXX;:llo:OXXXKXKOlccc.            
cXd,KXXXx.XXl'XXXXXXxkXXXXl                      ;OKKKK0kx0XXXKOdl;            .l0KXXxodXXXkoc,.           .,:oOXXXXXXXdXXXXXXX0kl,.                       dXNXXXXXXXXXXXXXXXX0,Ox;olxXXKXXKOlccc.           
OX0;:oxd,lKO;;XXXXXXdOXXXXl                      l0KKx0cO;dlXXKkKX.           ;OKKXXX00Kk:.                     .,l0XXXXXXXXOOd0XKkoc.                      cXNXXXXXXXXXXXXXXXXO;:0XXXXXXKKXKOocc:.          
OXXKOdodOXxcdKXXXXXKkOXXXXo                     .dKXKXXkkxkdXXO0Xk           cKK0O0kKXx'                            ,xXXXXXXXdd0XXXKOo:.  .'                 :XXXXXXXXXXXXXXXXXXKKXXXXXXXKKXXK0dcc:          
0XXXXXXXXXXXXXXXXXXO0KXXXXx                     .dKXKXXXXXXXXK0XX:          ;KKK0kkOXc         .'',,'...              ,0XXXXXOKXXXXXKKx:,  ,'                 cXNNNNXXXXXXXXXXXXXXXXXXXXXXXKKKK0occ,         
0XXXXXXXXXXXXXXXXXXOOXXXXXO                     'dKKKXXXK0000O0KX.         .OKOdkX0x'     .,cokOkX0OKKkOko:.            lXNXXXXXX0kxdOKkl;  .                  dNXNXXXXXXXXXXXXXXXXXXXXXXXXKXXXKOlcc.        
OXXXXXXXXKKKKKKKKKKKKKKKKK0                     'oKKKX0OXXXKKK000          cKXX00KK:    .lOKKkkl;:,,cooOXxOXOl'          'kXXXXXXK0dxdXKOo:                     kXXXXXXXXXXXXXXXXXXXXXXXXXXXKKXXKklc;        
0XXXXXXXK0000000OOOOOOOOOOO.                    .lKKO0cOox0XXXXXX          dKkkKKKl    'OO0o:.          ,oKXOXKx;.         :XXXXXXX00XXXX0d:   ,.               .OXXXXXXXXXXXXXXXXxOXXXKKXXXKKXKK0dcc.       
kXXXXXXXXXXXXXXXXXXXXXXXXXXo                    .c0XXXkkOx0XXXXXX.        .xXK0XXK     O0Kc  .colllo:.    .xXX0OKk,         :XXXXXXXXXKXXX0l:.  o                 kXXXXXXXXXXXXXXk,KXx:clcoKKxxKKKOl::       
0XXXXXXXXXXXXXXXXXXXXXXXXXXK                     cxXKXXXXXXXXXXXX:       . dKk0XXK    'KXO .dO;;''..l0kc    oXKKK0O; .       oXXXXXXXXcxk0KOlc  ..                .XXXXXXXXXXXXXX,:0O.OXXK'xKloKXKKxcc.      
kKXXXKocxX0XXXXXXXXXXXXXXXXX;                    ;lKKXXXXXXXXXXNNk       ; cKKKXXX'   .OXk '00dll;o, cX0d    OXXKkOk'         KNXXXXXXddxKKKdc'                    dXXXXXXXXXXXXX0o:,.0XKk.OXXXXXKKOoc;      
OXXXK,lOKX';lx0XXXXXXXXXXXXXO                    .ckXKXkxdXXXXXNNX.        .xKkKXX0.   c0K. :kKxxd,O  KX0,   :XXXXKKo .       oNXXXXXXKKXXXXOl:                    .XXXXXXXXXXXXXXXX0xK0llkXXXK0XXKKxl:.     
OddXO.OXX0.xO''0XXXXXXXXXXXXX:                ..  :l0X0OxlKXXXXXXNO       . 'x0K0XXk.   ;kOc'.';:;ko .XX0c   .XXXKx0k..       .XXXXXXXXXXXXKKxc.                    kXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKOoc'     
OkkXXxcllcoXk'OXXXXXXXXXXXXXXK.                l. .co0XXXKXXXXXXXXXd         .dKkKXX0,    ':ooollc' .xK00.   .XXX0KXO.         KXXXXXKdOkkKKK0l'                    ;XXXXXXXXXXXXXXXXXXKXXXXXXXKKXKK0xl:.    
OXKXXXXXKXXXxOXXXXXXXXXXXXXXXXk                 :  .loOKXXX00XXXXXXXd          ;kKKOXXd:.         .cx0O0;    lKKKkk0O.         OXXXXXKxl0okOKKd,                     kOOOOOOOOOOOO000O0KXXXXXXXXXKKKKkoc.    
OXKXXXXXXXXXXXXXXXXXXXXXXXXXNXXo                 .  .clkKKkdx0XXXXXXXk.          ,lxK0xK0do:;,::ckkK0kl.    .0KOKKXKd          k00KKKXXX0OXKKKx;                     xKKKKKKKKKKKKKKKKKXXXXXXXXX0KXKKOdo'    
OKXKKXXXXXXXXXXXXXXXXXXXXXXXNNNX:                     ,cxKOxxxXXXXXXXXK:            .;lxkkKKOOK0kOd:'      .d0XdxkK0'          KK000000KXXXKXKk;                     lXXXXXOOKXXXXXXXXXXXXXXXXXXKXKKK0xd'.   
xKKKKXXXXXXXXXXXXXXXXXXXXXXXNNNNX'                 ;.  .:o0KXXXXXKkXXXXXk,               ..'','..         ;K0kOKKKKl          .XX0KXXXXXXXXKKKk,                     :XXXXXOOKXXXXXXXXXXXXXXXXXXXXKKKKkd;.   
c0KXXXKXXXXXXXXKXXXXXXXXXXXXXXXNNK:                 '.  .;lkKXXXKxoKXXXXXXO:.                           .oXXx00KKKd           lX0KXXxxxkxKXKKKx.                     ,XXXXOxKXXXXX0lcoX0dodkXXXX0KKKKKkd;.   
:o0KXKKXXXXXXk:;dXXXXXXXXXXXXXXXXNXx                      .;oOKX0xOkXXXXXXXXKd;.                     ':x000XXX0KOc            0KOXXXdd,kokkXKKd                      'XXXXxdKXXXXK.oOKd'oxdc:KXKKXKKKKOd:.   
:co0KXXKKXOll,kK;kXXXXXXXXXXXXXXXXNNO.                      .;oxOKXXXXX0xXXXXXXXkoc;..          .':oOXXXxodKXKk;.            ,loOKXXXKkkOKKKKOl                      ,XXXKkdXXXXX0.xXX;cXXX0.0Xx:KXKKK0xo'   
;ccokKKKXXXkclllc'0XXXXXXXXXXXXXXXXXXK;                       ..;okKKXX0dKXXXKxxxKXXX0xkkxx:ldc0KXOxdOXXXX00x;              :K0kdddxk0XXXKKK0o.                      ;XXXKOkXXXXXXk:;:,.;cc:dXXKKXKKKK0xo'   
.ccccx0KXxkXXXXKxckXXXXXXXXXXXXXXXXXXXXd.                         .;okO0XXXXXkkOlXXXKoOkXXXk0dd0XXK0OKKK0kc.               ,XXXK0XK0kkOXKKKKx.                       cXXXOOxXXXXXXXXKOkxxxkKXXXK0KKKKK0x:.   
 .cllcd0KKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK:                           ..;ldkO0KKKKXXXXXxKXXXXX0OKKK00Odl;.                .oXXXXdlxkO0KXKKKK0,                        l0KKKKKXXXXXXXXXXXXXXXXXXXKKKKKKK0d'.   
  .lllco0KXKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx'                              ..':ldkOOO0000000OOOOkdc;'.                   .OXXXXXxkXOddO0KKKKl                         .':oxO0KXKKKKXXXXXXXXXXXXXXXXXKKKOd,    
   .,cccoOKXXXKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx'                                  ......''''......                       ,OXXXXXXKKXXXXXkXKKd.                        .c:;,,,,;:ldk0KXXKKKKKKXXXK0KXXKKKOo;    
     .:clox0KKKXXXXXXX0ddodXXXXXXXXXXXXXXXXXXXx,                                                                     .oXXXXXXXXXXXXXXKXXKd.                         :KKK00Okxol:;::clodxxOKXXXXXXXKKKKOl.    
.      ,loloOKKXKXXXXx:OKKOXXXXXXXXXXXXXXXXXXXXXk:                                                                 .cKXXKkOxddkXXXXKKXK0l.                          OXXXXXXXXXXKK00OOkxdoo0XXK0KXXXKXKO:     
;.      .:llldOKKXXKXd:dxokXOcXXXXXXXXXXXXXXXXXXXXKo'                                                            .lKXXXXldk,kO;XXXKXKKO;                           ,XXXXXXXXXXXXXXXXXXXXXKXXXXKKKKKKXKx,     
 ..       ,ccccokKKKX0OOk'kkolXXXXXXXXXXXXXXXXXXXXXXX0d;.                                                     .lkXXXXXXX0dxoxxxKKXKK0d.                            OXXXXXXXXxcxKXXXXXXXXXXXXXXXKKKKXX0o.     
           .:ccccdOKXdxXXOodOXXXXXXXXXXXKXXXXXXXXXXXXXXXKd;.                                                ;xXXXXXXXXXXXXXXXXxKKK0kl.                            ,XXXXXXXXXd :;cdO0KXXXXXXXK0XKKKKXKO:      
             'clcclx0KXXKKXXXXXXXXXXX0do,XXXXXXXXXXXXXXXXXX0xc'.                                        .'d0XXXxclxdOXXXXXXXXKKK0kc.                              OXXXXXXXXX0.xKxoccccc:cKXXXKKKKKKX0d'      
      .,.      .;:;:ldOKKXXKXXXXXXXXdoOx;XXXXXXXXXXXXXXXXXXXXXNX0xl;..                              .ox0XKXXXXcdxxl0cXXXKXKKK00kl.                              .OXXXXXXXXXXX;,XXXXXXXKKKXO:kKKKKKKKkc       
        cd;      .':::ldxOKKXXKXXXXXXXk:KXdlXXXXXXXXXXXXXXXXXXXXXXXXXKOxdlc:,'............',;:ll.ckOolXXXXXXXXdxxxlXKXKXKK000ko'                                xXXXXXXXXXXXXk:KXXXXXXXXXX0x0XKKKXX0d,       
         .ld,       ';:::ldk0KKXXKXXXXo:kx:lXXXXXXXXXOkXXXXXXXXXXXXXXXXXXXXXXXNXXXXKOKXXXNXXXXX,kXXXllOo0XXXXXXXKKX0kKK000Okl'                                 lXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKXKkl        
            ...       .,;::clxO0KKXX0dXOxkKXXXXXXXXXXO.0XXXXXXXXXX0xxxddKdOXXXXXXXXO,XNKkXXXXXXodxdolllOXXXXXXXXXKKK000Okl;.                                  :XXXXXXXXXXXXXXXXXXXXXXXXXXKKXXXXXKXOo'        
                         .';c::oxO0KKKXXKXXXXXXXXXXXXXocXKXXXXXXXXXKOocxk xXXXXXXXK,OXX;kXXXXXXXK00k:dXXXXXXKKKKK000OOo;.                                    ;XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKX0d:         
                            ;o;;cldk0KXXXXXOXXXXXXXXXX0.coXXXXXXXXXk'oXXx.OXXXXXXXo,XXx:XXXXXXXXXXXXXKXXXKXKK000000kxd.                                      KXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKKKKXkc.         



"""

tiempo2 = """
MMMMMWWNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXMMMMMMMMMMMMMMMMMMMMMMMWMMMMMMMMMMM
MMMWWWWNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXKkdc:;,,''''''''',,;ldOKXXXXXXXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXX0o;'.,:cllllccccccccllll:,'.':dKXXXMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMNNNNNNNNNNXXXXXXXXXXXXXXXXXXk:'';llc:::;;;;;;;;;;;;;;;;::ccl:,.'lOMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMNNNNNNNNNNXXXXXXXXXXXXXXX0l.':lc:;;;;,'...'',,,,'''....';;;;;:cc,.'kMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMNNNNNNNNNNXXXXXXXXXXXXX0:.;c:;;;;,..,:ox00KKKKKKKKKK0kd:,...,;;;:c:..dWMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMNNNNNNNNNNXXXXXXXXXXXKc.;c:;;;,..;d0KKXXXXXXXXXXXXXXXXXXKKkc...;;;;::..dXXXXXXXXXXXXXXXXXXXXXXXNMMMMM
MXK0000OOOOOOOOOOkkkkk0XXXXx.':;;;;,.'o0KXXXXXXXXXXXXXXXKXXXXXXXXXXKk; .;;;;:, ,0XXXXXXXXXXXXXXXXXXXXXXNMMMM
MMMMMMMNNNNNNNNNNXXXXXXXXXl ;;;;;,..xKXXXXXXXXXXXXXXXKl. kXXXXXXXXXXXX0; .;;;;;..kXXXXXXXXXXXXXXXXXXXXXNMMMM
MMMMMMMNNNNNNNNNNXXXXXXXX; ;;;;;. oKXXXXXXXXXXXXXXXKl'lO' kXXXXXXXXXXXXXk. ,;;;;. xXXXXXXXXXXXXXXXXXXXXNMMMM
MMMMMMMKKKKKK0000OO0XXXX: ,;;;;..OXXXXXXXXXXXXXXXXK:.,lOx. kXXXXXXXXXXXXXK; ';;;;. kXXXXXXXXXXXXXXXXXXXNMMMM
MMMMMMWOOOO000000OO0XXXd ';;;,..0XXXXXXXXXKKXXXXXXXXX..; ddOXXXXXXXXXXXXXXX; ';;;; .KXXXXXXXXXXXXXXXXXXNMMMM
MMMMMMMNNNNNNNNNNXXXXXK .':dkkkkkkkkxxdcxKKKXXXXXXXXK ;.'XXXXXXXXXXXXXXXXXXK' ,;;;, :XXXXXXXXXXXXXXXXXXNMMMM
MMMMMMMNNNNNNNNNNXXXXXc ,cWWWWWWWWWWWWWKooKKXXXXXXXXk c lXXXXXXXXXXXXXKXXXXXO .;;;;. KXXXXXXXXXXXXXXXXXNMMMM
MMMMMMMWWNNNNK000O0XXX. 'OWWWWWWWWWWWWNNodxXXXXXXXXXl ; 0XXXXXXXXXXXXXXKXXXXX, ;;;;' oXXXXXXXXXXXXXXXXXNMMMM
M000K00OOO00OOOOOkkkKK .'0NWWWWWWWWWNNNX:okXXXXXXXKc.,. d0XXXXXXXXXXXXo:OXXXXd ';;;, :XXXXXXXXXXXXXXXXXNMMMM
MMMMMMMNNNNNNNNNNNNNX0 .'ONNWWddxxxkxxd:loXXXXXXXXl dOO. :;::::coxk0K0.. dXXXk .;;;; ,XXXXXXXXXXXXXXXXXNMMMM
MMMMMMMNNNNNNNNNNNNNNX .,xNNWWoXXXKXXXXO0XXXXXXXXX0;.''',;;;cldxdoc::;'kc cKXx ';;;; ;XXXXXXXXXXXXX0OKONMMMM
MMMMMMMMWWWNWNWNNNWNNW..;lNNWWlXXXXXXXXXXXXXXXXXXXXXXKKXXXXKkdl::;;;:lkOOo ;Xc ,;;;, oXXXXXXXXXX0Kd0MMkkKWMM
MMMMMMMMMMMMMMMMMMMMMMc ,:XK0KcXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXK, o::cxKK..;;;;. xXXXXXXXXOkWN0KK0OMMlMM
MMMMMMKOOOOOOOOOOOO0WWK .loxkkdkOO0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:;o0XXXX: ,;;;, ;,XXXXXXXX:NXMMMlMMNkdXM
MMMMMMMMMMMMMMMMMMWXXXX;:0WMMMMMNMxXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXo ';;;;..NcOXXKkxxll0KXXXkkKKWNoM
MMMMMMMMMMMMMMMMMMWXXXdNMMMMMMMMO0dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXKc ';;;;. 0WXlkkOXWWXoxXMMMNxOX0lMM
MMMMMMMMMMWWNNNNNNNXXXkWWWMMMMMMMMNkXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0' ,;;;;..0WWWWWWWWWNXxckk0KK0lXK0MM
MMMMMMMMMNNNNNNNNNNXXX00NNNNNWNNkkl.dXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0c .;;;;;..0WWWWWWWXOxxx0XXKXXXXXNMMMM
MMMMMMMMMNNNNNNNNNNXXXXOOkOO;'l:,;;' .oKXXXXXXXXXXXXXXXXXXXXXXXXXXXXO:..;;;;;, 'oKXKOOOkkkKXXXXXXXXXXXXNMMMM
MMMMMMMMMNNNNNNNNNNXXXXXXXXX0; .;;;;;,..;dKXXXXXXXXXXXXXXXXXXXXXXOl'.';;;;;,..xXKOkOKXXXXXXXXXXXXXXXXXXNMMMM
MMMMMMMMMNNNNNNNNNNXXXXXXXXXXXO; .,;;;::,. .:dOKXXXXXXXXXXXK0xl,..';;;;;c;..dXXXXXXXXXXXXXXXXXXXXXXXXXXNMMMM
MMMMMMMMMNNNNNNNNNNXXXXXXXXXXXXX0c..,:::;';l,  ..',;;;;;,,'...,;;;;;;::;.;xXXXXXXXXXXXXXXXXXXXXXXXXXXXNWMMMM
MMMMMMMWWNNNNNNNNNNXXXXXXXXXXXXXXXXk;';:;,NWWKc..;;;;;;;;;;;;;;;;;;;,.;dKXXXXXXXXXXXXXXXXXXXXNNNNNNMMMMMMMMM
MMMMMWWWMNNNNNNNNNNXXXXXXXXXXXXXXXXXXXOl;NWWNNNl .;;;;;;;;;;;;,'..,lkKXXXXXXXXXXXXXXXXXXXXXXXNNNNNNMMMMMMMMM
MMX000000OOOO0Ncl:xdxxOXXXXXXXXXXXXXXX0cNWWNNXc'..........',;cok0KxdXXXXXXXXXXXXXXXXXXXXXXXXXNNNNNWMMMMMMMMM
MMWNNNNNNKOOO0N.k,dold:xKKK0oOOkOOOOOxcNWWNNxlKXXXXKKKKKKOkkOOKWWWW0:XXXXXXXXXXXXXXXXXXXXXXXNMMMMMMMMMMMMMMM
MMMMMMMMMNNNNNN.d;loddlMMMMWcWWWWWWNXNWWNNOckXXXXXXXXXXXXXXXXXOcKWWW,KXXXXXXXXXXXXXXXXXXXXXXNMMMMMMMMMMMMMMM
MMMMMMMMMNNNNNN.:lOkOk;kXNWNcWWWWWWWNNNXxldXXXXXXXXXXXXXXXXXXXXlkWWW:kXXXXXXXXXXXXXXXXXXXXXXNMMMMMMMMMMMMMMM
MMMMMMMMMNNNNNN.:oxxk:olcOkOxkkkOkkxxxkx0XXXXXXXXXXXXXXXXXXXXXXlOWWNldXXXXXXXXXXXXXXXXXXXXXXNMMMMMMMMMMMMMMM
MMMMMMMMMNNNNNN.coxklcO0XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:KWNNooXXXXXXXXXXXXXXXXXXXXXXNMMMMMMMMMMMMMMM
MMMMMMMMMNNNNNN.loxx:oXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX,OOOOolXXXXXXXXXXXXXXXXXXXXXXNMMMMMMMMMMMMMMM
MMMMMMWXX0000XN'd:kkl:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX0xxxxxXXXXlMMMMXoXXXXXXXXXXXXXXXXXXXXXXNMMMMMMMMMMMMMMM
MMMMMMMMMNNNkON;kdcc,xXXXXXXXXXXXXXXXXXXXXXKxxxxxxxxxxxxxxxxKXXoMMMMOckKXXXXXXXXXXXXXXXXXXXXNMMMMMMMMMMMMMMM
MMMMMMMMMNNNNNNXxkdxKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXO,00Ok:dd:KXK0Ok0XXXXXXXXXXXXXNMMMMMMMMMMMMMMM
MMMMMMMMMNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX;llddkOOddlcldxx:,0XXXXXXXXXXXWMMMMMMMMMMWMMMM
MMMMMMMMMNNNNNNNNNNNNXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.doxcxOOxxxkxkdl;X.XXXXXXNNNWWMMMMMMMMMMWWMMMM
MMMMMMMMMNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNO,kxxdkkxddxdddxkOxdNNNNNNWMMMMMMMMMMMMWWWMMMMM

"""